/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.component;

import com.model.Model_User_Account;
import java.awt.Color;

/**
 *
 * @author Knomjean
 */
public class Chat_Title extends javax.swing.JPanel {

    
    public Model_User_Account getUser() {
        return user;
    }

    private Model_User_Account user;
    
    public Chat_Title() {
        initComponents();
    }
    public void setUsername(Model_User_Account user){
        this.user = user;
        lbName.setText(user.getUserName());
        if(user.isStatus()){
            statusActive();
        }else{
            setStatusText("Offline");
        }
        
    }
    public void updateUser(Model_User_Account user){
        if(this.user == user){
            lbName.setText(user.getUserName());
            if(user.isStatus()){
                statusActive();
            }else{
                setStatusText("Offline");
            }
        }
    }
    private void statusActive(){
        lbStutus.setText("Online");
        lbStutus.setForeground(new java.awt.Color(150, 193, 110));
    }
    private void setStatusText(String text){
        lbStutus.setText(text);
        lbStutus.setForeground(new Color(160,160,160));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layer = new javax.swing.JLayeredPane();
        lbName = new javax.swing.JLabel();
        lbStutus = new javax.swing.JLabel();

        setBackground(new java.awt.Color(207, 201, 231));

        layer.setFont(new java.awt.Font("Mitr Light", 0, 12)); // NOI18N
        layer.setLayout(new java.awt.GridLayout(0, 1));

        lbName.setFont(new java.awt.Font("Mitr Light", 1, 12)); // NOI18N
        lbName.setForeground(new java.awt.Color(51, 51, 51));
        lbName.setText("Name");
        layer.add(lbName);

        lbStutus.setFont(new java.awt.Font("Mitr Light", 0, 12)); // NOI18N
        lbStutus.setForeground(new java.awt.Color(71, 188, 42));
        lbStutus.setText("Online ");
        layer.add(lbStutus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(layer, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(layer)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane layer;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbStutus;
    // End of variables declaration//GEN-END:variables
}
